# Generated by Django 3.0.4 on 2020-03-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblogs',
            options={'verbose_name': '我的博客', 'verbose_name_plural': '我的博客'},
        ),
    ]
