# Generated by Django 3.0.4 on 2020-03-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200314_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblogs',
            options={'verbose_name': '技术类', 'verbose_name_plural': '我的博客'},
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='pub_date',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
