# Generated by Django 3.0.4 on 2020-03-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200315_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblogs',
            options={'verbose_name': '我的博客', 'verbose_name_plural': '我的博客'},
        ),
        migrations.RenameField(
            model_name='myblogs',
            old_name='question_text',
            new_name='title',
        ),
    ]
